version: '3.3'

services:
  api:
    container_name: api
    build:
      context: api
      args:
        src_path: src/github.com/doutori/grpc-sample/go-api
    ports:
      - "8080:8080"
    # volumes:
    #   - ./go-api:/go/src/github.com/doutori/grpc-sample/go-api
    #   - /go/src/github.com/doutori/grpc-sample/
    # command: realize start -path="." --no-config --run
    command: go run main.go
  web:
    container_name: web
    build:
      context: web
    ports:
      - "3000:3000"
    command: npm start
